# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f64486c8-9944-4e44-ae2d-269ff5e21652";
    fsType = "ext4";
  };

  fileSystems."/mnt/Media" = {
    device = "/dev/disk/by-uuid/955df379-9988-4bf1-8b25-faa9cc0f4aa0";
    fsType = "ext4";
    options = ["nofail"];
  };

  boot.initrd.luks.devices."luks-537c30d5-d4b6-4f51-a046-52977a57e5ab".device = "/dev/disk/by-uuid/537c30d5-d4b6-4f51-a046-52977a57e5ab";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A332-79CC";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp134s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp132s0f0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.enableRedistributableFirmware = true;
}
